### ISSUE TITLE
number of fetched items

### ISSUE THREAD

**Issue by martinle068** [IcySnex/YouTubeMusicAPI#1]
would it be possible to define a number of items to be fetched?

**Comment by IcySnex** [comment]
Hello,

Are you referring to searching for a query or fetching songs from an album/playlist?

Kind regards.

**Comment by martinle068** [comment]
Hello,
thank you for your response.
I'm referring to searching for a query, currently it only returns 20 items, specifically I'm searching for Songs.
Would it be possible to define a number of items I would want it to return?

Thank you,
Martin

**Comment by IcySnex** [comment]
Hello,

Yes, it would definitely be possible to do implement such a thing and I actually just did in [Version 1.2.0](https://github.com/IcySnex/YouTubeMusicAPI/releases/tag/v1.2.0)! Thanks for this suggestion.

There is now a simple `limit` parameter when using the "direct" way of searching which can be used like this: `ytmClient.SearchAsync<Song>(query, limit)`. This should handle the basic needs of wanting to list more items.

However, for more complex things, I would recommend doing the search via “shelves”. This way you can, for example, load more search results as the user scrolls down the page, just like the real YouTube Music!! This works by returning only "parts" of the search results (20 per request) with a "next continuation token" which then can be used to send another request when needed (e.g. scrolling down or going to the next page).

I have also explained this in the [README](https://github.com/IcySnex/YouTubeMusicAPI?tab=readme-ov-file#shelves). I didn't create any example for an UI with dynamic loading but it shouldn't be too hard. For a rough orientation you can look at the [internal code of the "simple" searching with a limit](https://github.com/IcySnex/YouTubeMusicAPI/blob/main/YouTubeMusicAPI/Client/YouTubeMusicClient.cs#L231-L252).



Kind regards.

**Comment by IcySnex** [comment]
If you have any further questions, please don't hesitate to ask! If everything is working please close this issue. Thank you

**Comment by martinle068** [comment]
Thank you very much, that's perfect.
