### ISSUE TITLE
Question: Official NuGet Repository?

### ISSUE THREAD

**Issue by formeo14** [IcySnex/YouTubeMusicAPI#3]
Is there an official NuGet release available on a NuGet repository such as NuGet.org?

**Elaboration:** I've noticed that the release includes NuGet packages. However, I couldn't find a dedicated NuGet package repository that supports automatic build workflows. Could you provide more information on whether such a repository exists or if there are any plans to set one up in the future?

**Comment by IcySnex** [comment]
Hello, thank you for your question.

Yes, there is an official NuGet release which is always updated alongside the GitHub release. You can find it on [nuget.org](https://www.nuget.org/packages/YouTubeMusicAPI)
